### ISSUE TITLE
Unknown option --node-ipc when starting the tslint server

### ISSUE THREAD

**Issue by dorogoy** [Microsoft/vscode-tslint#352]
- tslint Version: 5.10.0
- typescript Version: 2.9.1
- Visual Studio Code: 1.24.0

Steps to Reproduce:

1. Just activate the linter and vscode will start showing multiple outputs about the tslint server crashing:

```
[Info  - 10:44:41] Linter is running.

  error: unknown option `--node-ipc'

[Info  - 10:44:58] Connection to server got closed. Server will restart.
[Info  - 10:44:58] Linter has stopped.
```

> The tslint server crashed 5 times in the last 3 minutes. The server will not be restarted.

**Comment by egamma** [comment]
@dorogoy I haven´t seen any other reports like this. On what platform does this happen? Can you enable tracing as described here https://github.com/Microsoft/vscode-tslint/blob/master/tslint/README.md#trouble-shooting

**Comment by dorogoy** [comment]
Hello @egamma, this is on macOS High Sierra (10.13.4)
The only thing I can have a bit different is that I am using [nvm](https://github.com/creationix/nvm) to have different versions of node installed.
I already tried to uninstall, remove the directory and reinstall vscode-tslint with no success.
Thanks for your help!

```
[Info  - 09:22:22] Linter is running.
[Trace - 09:22:22] Sending notification 'initialized'.
Params: {}


[Trace - 09:22:22] Sending notification 'workspace/didChangeConfiguration'.
Params: {
    "settings": {
        "tslint": {
            "enable": true,
            "jsEnable": false,
            "rulesDirectory": "",
            "validateWithDefaultConfig": false,
            "configFile": "",
            "ignoreDefinitionFiles": true,
            "exclude": "",
            "run": "onType",
            "nodePath": "/Users/srael/.nvm/versions/node/v9.11.1/bin/",
            "autoFixOnSave": false,
            "alwaysShowRuleFailuresAsWarnings": false,
            "alwaysShowStatus": false,
            "trace": {
                "server": "verbose"
            },
            "packageManager": "npm"
        }
    }
}


[Trace - 09:22:22] Sending notification 'textDocument/didOpen'.
Params: {
    "textDocument": {
        "uri": "file:///Users/srael/Proyectos/smartie-material/src/app/users/users.component.ts",
        "languageId": "typescript",
        "version": 1,
        "text": "import { Component, OnInit } from '@angular/core';\nimport { Title } from '@angular/platform-browser';\nimport { MatSnackBar } from '@angular/material/snack-bar';\n\nimport { TdLoadingService } from '@covalent/core/loading';\nimport { TdDialogService } from '@covalent/core/dialogs';\nimport { TdMediaService } from '@covalent/core/media';\n\nimport { UserService, IUser } from './services/user.service';\n\n@Component({\n  selector: 'sie-users',\n  templateUrl: './users.component.html',\n  styleUrls: ['./users.component.scss'],\n})\nexport class UsersComponent implements OnInit {\n\n  users: IUser[];\n  filteredUsers: IUser[];\n\n  constructor(private _titleService: Title,\n              private _loadingService: TdLoadingService,\n              private _dialogService: TdDialogService,\n              private _snackBarService: MatSnackBar,\n              private _userService: UserService,\n              public media: TdMediaService) {\n  }\n\n  ngOnInit(): void {\n    this._titleService.setTitle('SmartIE Users');\n    this.load();\n  }\n\n  filterUsers(displayName: string = ''): void {\n    this.filteredUsers = this.users.filter((user: IUser) => {\n      return user.displayName.toLowerCase().indexOf(displayName.toLowerCase()) > -1;\n    });\n  }\n\n  async load(): Promise<void> {\n    try {\n      this._loadingService.register('users.list');\n      this.users = await this._userService.query().toPromise();\n    } catch (error) {\n      this.users = await this._userService.staticQuery().toPromise();\n    } finally {\n      this.filteredUsers = Object.assign([], this.users);\n      this._loadingService.resolve('users.list');\n    }\n  }\n\n  delete(id: string): void {\n    this._dialogService\n      .openConfirm({message: 'Are you sure you want to delete this user?'})\n      .afterClosed().toPromise().then((confirm: boolean) => {\n        if (confirm) {\n          this._delete(id);\n        }\n      });\n  }\n\n  private async _delete(id: string): Promise<void> {\n    try {\n      this._loadingService.register('users.list');\n      await this._userService.delete(id).toPromise();\n      this.users = this.users.filter((user: IUser) => {\n        return user.id !== id;\n      });\n      this.filteredUsers = this.filteredUsers.filter((user: IUser) => {\n        return user.id !== id;\n      });\n      this._snackBarService.open('User Deleted', 'Ok');\n    } catch (error) {\n      this._dialogService.openAlert({message: 'There was an error trying to delete the user'});\n    } finally {\n      this._loadingService.resolve('users.list');\n    }\n  }\n\n}\n"
    }
}


[Trace - 09:22:22] onDidChangeConfiguraton
[Trace - 09:22:22] validateAllTextDocuments
[Trace - 09:22:22] onDidOpen
[Trace - 09:22:22] triggerValidation on file:///Users/srael/Proyectos/smartie-material/src/app/users/users.component.ts
[Trace - 09:22:22] onDidChangeContent
[Trace - 09:22:22] SettingsCache: cache updating cache forfile:///Users/srael/Proyectos/smartie-material/src/app/users/users.component.ts
[Trace - 09:22:22] Received request 'workspace/configuration - (0)'.
Params: {
    "items": [
        {
            "scopeUri": "file:///Users/srael/Proyectos/smartie-material/src/app/users/users.component.ts",
            "section": "tslint"
        }
    ]
}


[Trace - 09:22:22] Sending response 'workspace/configuration - (0)'. Processing request took 4ms
Result: [
    {
        "enable": true,
        "jsEnable": false,
        "rulesDirectory": "",
        "validateWithDefaultConfig": false,
        "configFile": "",
        "ignoreDefinitionFiles": true,
        "exclude": "",
        "run": "onType",
        "nodePath": "/Users/srael/.nvm/versions/node/v9.11.1/bin/",
        "autoFixOnSave": false,
        "alwaysShowRuleFailuresAsWarnings": false,
        "alwaysShowStatus": false,
        "trace": {
            "server": "verbose"
        },
        "packageManager": "npm",
        "workspaceFolderPath": "/Users/srael/Proyectos/smartie-material"
    }
]


[Trace - 09:22:22] onDidChangeContent: settings[object Object]
[Trace - 09:22:22] onDidChangeContent: triggerValidateDocument
[Trace - 09:22:22] triggerValidation on file:///Users/srael/Proyectos/smartie-material/src/app/users/users.component.ts
[Trace - 09:22:22] trigger validateTextDocument
[Trace - 09:22:22] start validateTextDocument
[Trace - 09:22:22] SettingsCache: cache hit for file:///Users/srael/Proyectos/smartie-material/src/app/users/users.component.ts
[Trace - 09:22:22] validateTextDocument: settings fetched
[Trace - 09:22:22] validateTextDocument: about to load tslint library
[Trace - 09:22:22] loadLibrary for file:///Users/srael/Proyectos/smartie-material/src/app/users/users.component.ts
[Trace - 09:22:22] SettingsCache: cache hit for file:///Users/srael/Proyectos/smartie-material/src/app/users/users.component.ts
[Trace - 09:22:22] NODE_PATH value is: /Users/srael/.nvm/versions/node/v9.11.1/bin/
[Trace - 09:22:22] validateTextDocument: loaded tslint library

  error: unknown option `--node-ipc'

[Error - 09:22:23] Connection to server got closed. Server will not be restarted.
[Info  - 09:22:23] Linter has stopped.
```

**Comment by egamma** [comment]
@dbaeumer the trace shows that vscode and tslint server are successfully talking, but after the tslint module is loaded there is an error.

**Comment by dbaeumer** [comment]
The error doesn't seem to come from the original start of the tsserver. Otherwise there wouldn't have been any communication. Does the tslint server fork any new node instance? Fork usually passes on the original command line args which would explain why `--node-ipc` is carried on. It is a valid argument to the node LSP server. 

The server stop could be caused by the `spawn` bug I fixed last week. Can you update to the lastest LSP libraries and see if the error still exists.

**Comment by dorogoy** [comment]
@dbaeumer thank you very much for your help. Could you explain what I have to do to update the LSP libraries? I am a bit lost here, sorry.

**Comment by egamma** [comment]
@dorogoy I´ve just discussed it with @dbaeumer the `spawn` bug he mentioned happened on Windows but you are on OS X, so updating the libraries might no help.

Looking at the trace again, the error happens before the validation by tslint starts, this means when tslint is loaded. Do you use custom tslint rules that spawn a process? Can you reproduce the issue when you use a minimal `tslint.json` file with only built-in rules, e.g. 

`tslint.json`

```json
{
    "rules": {
        "no-var-keyword": true,
    },
    "defaultSeverity": "warning"
}
```

**Comment by dorogoy** [comment]
@egamma for a moment I tough this was the problem because I am using the `tslint.json` file from Covalent. To my eyes it is very similar to the standard one from Angular Cli:

https://github.com/Teradata/covalent/blob/develop/tslint.json

But no way, the problem still there even if I change the file with yours. 
I am the only one on my team to use vscode but I can ask one of my colleagues to copy my setup and check if this happens too.

**Comment by dorogoy** [comment]
@egamma you are right! The problem was related with my `tslint.nodePath`. It should point to the `tslint` module path but I had it pointing to the bin symbolic link ¿¿??  Everything was my fault :( Thank you so much for your time and your help 👍 I close the "non issue".
